apiVersion: apps/v1
kind: Deployment
metadata:
  name: innoscripta-php-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: innoscripta-container
          image: shaheer4636/php-app
          ports:
            - containerPort: 80  
